name: 'Matrix Notify'
description: 'Send a matrix notification'
branding:
  icon: message-square
  color: yellow
inputs:
  matrix_token:
    description: Access token for Matrix bot account
    required: true
  github_token:
    description: The GitHub token for accessing workflow info
    required: true
  roomid:
    description: Matrix room ID to send message to (default is SunPy Development room)
    required: true
  homeserver:
    description: Matrix homeserver
    required: false
    default: 'https://matrix.org'
  ignore_pattern:
    description: A regex to apply to reaction names to ignore certain jobs.
    default: ''
outputs:
  eventid: # id of output
    description: 'The matrix event ID of the sent message.'
runs:
  using: 'node16'
  main: 'index.js'
