name: Test Matrix

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: succeeded
        with:
          status: Succeeded
          token: ${{ secrets.matrix_access_token }}
          homeserver: 'https://matrix.cadair.com'
          roomid: '!vuSqbfLVzKegOeHbhL:matrix.org'

      - name: Print the event ID
        run: echo "Sent Matrix Event ${{ steps.succeeded.outputs.eventId }}"
