name: Test Success Summary

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pass:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  a_really_long_job_name:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: [pass, fail, a_really_long_job_name]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          matrix_token: ${{ secrets.matrix_access_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          homeserver: 'https://matrix.cadair.com'
          roomid: '!vuSqbfLVzKegOeHbhL:matrix.org'
          ignore_success: true

      - name: Print the event ID
        run: echo "Sent Matrix Event '${{ steps.message.outputs.eventId }}'"

